local builtin = require('telescope.builtin')
vim.keymap.set('n', '<M-o>', builtin.find_files, {})
vim.keymap.set('n', '<M-i>', builtin.buffers, {})
vim.keymap.set('n', '<C-P>', builtin.git_files, {})
vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
vim.keymap.set('n', '<leader>ps', function() builtin.grep_string({search = vim.fn.input("Grep: ")}) end)
